### ISSUE TITLE
DictDmrs links

### ISSUE THREAD

**Issue by guyemerson** [delph-in/pydmrs#2]
Second index by label, rather than end.
Return the whole link, rather than label.

**Comment by emm68** [comment]
Aren't we dropping the second index altogether?

**Comment by guyemerson** [comment]
We can do that.  My mistake.

**Comment by guyemerson** [comment]
Sorry, I didn't see you self-assigned this!  Check the latest commit?

**Comment by emm68** [comment]
That's alright. I started working on it earlier today and thought I'd assign the issue so that we don't double the work but it seems you finished faster :)

**Comment by guyemerson** [comment]
Okay.  Let me know if there's any part of it you'd like to do differently.
