### ISSUE TITLE
Wrong citation year in README

### ISSUE THREAD

**Issue by goodmami** [delph-in/pydmrs#20]
Just a documentation bug.

The README says Copestake 2007, but it's actually 2009.

Also, if you put bullets before the citations, they will appear as a list:

``` markdown
- [Copestake (2009)](http://www.aclweb.org/anthology/E/E09/E09-1001.pdf)
- [Copestake et al. (2016)](http://www.lrec-conf.org/proceedings/lrec2016/pdf/634_Paper.pdf)
```

Alternatively, a blank newline between them will present them on separate lines.

(and if editing the README, maybe add some more info, like installation instructions, basic usage, requirements, etc. There should be some basic info for people coming to get the new release (e.g. from LREC), although I now notice the Copestake et al. (2016) paper doesn't have a link to pydmrs)

**Comment by anncopestake** [comment]
yes - there's a link in the paper to a wiki page which has hardly 
anything on it ... I will try and instantiate it further over the next 
few days.

Ann

**Comment by guyemerson** [comment]
Thanks, Mike.  I'll update the README soon!
